// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.config.security;

import com.uol.comp3011.coursework1.dal.repository.RoleRepository;
import com.uol.comp3011.coursework1.dal.repository.UserRepository;
import com.uol.comp3011.coursework1.dal.entity.User;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

@Component
public class AdminSeeder implements ApplicationRunner {

  private final UserRepository userRepo;
  private final RoleRepository roleRepo;
  private final PasswordEncoder encoder;

  @Value("${app.seed.admin.email:admin@example.com}")
  private String adminEmail;

  @Value("${app.seed.admin.password:admin}")
  private String adminPassword;

  public AdminSeeder(
      UserRepository userRepo, RoleRepository roleRepo, PasswordEncoder passwordEncoder) {
    this.userRepo = userRepo;
    this.roleRepo = roleRepo;
    this.encoder = passwordEncoder;
  }

  @Override
  @Transactional
  public void run(ApplicationArguments args) {

    User admin = userRepo.findByEmail(adminEmail);
    if (admin == null) {
      // If admin user doesn't exist, create it.
      admin = new User();
      admin.setEmail(adminEmail);
      admin.setPasswordHash(encoder.encode(adminPassword));
    }

    admin.getRoles().add(roleRepo.findByName("ROLE_USER"));
    admin.getRoles().add(roleRepo.findByName("ROLE_ADMIN"));

    userRepo.save(admin);
  }
}
