// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.config.security;

import io.jsonwebtoken.JwtException;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.slf4j.MDC;
import org.springframework.http.HttpHeaders;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;

@Component
public class JWTAuthenticationFilter extends OncePerRequestFilter {

  private final JWTUtils jwtUtil;
  private final UserDetailsService userDetailsService;

  public JWTAuthenticationFilter(JWTUtils jwtUtil, UserDetailsService userDetailsService) {
    this.jwtUtil = jwtUtil;
    this.userDetailsService = userDetailsService;
  }

  /**
   * Filters incoming requests for a JWT token, and validates before allowing the application to
   * send a response.
   *
   * @param request A HTTP request.
   * @param response A HTTP response.
   * @param filterChain A filterChain object.
   * @throws UsernameNotFoundException If the user doesn't exist.
   * @throws JwtException If error occurs while validating JWT.
   * @throws ServletException For issues when passing request to next filter in the chain.
   * @throws IOException For issues when passing request to next filter in the chain.
   */
  @Override
  protected void doFilterInternal(
      HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
      throws UsernameNotFoundException, JwtException, ServletException, IOException {

    // Get request header.
    String authHeader = request.getHeader(HttpHeaders.AUTHORIZATION);

    if (authHeader != null && authHeader.startsWith("Bearer ")) {
      // Extract bearer token.
      String token = authHeader.substring(7);

      if (jwtUtil.isValid(token)
          && SecurityContextHolder.getContext().getAuthentication() == null) {
        /* If token valid and application security context available, then
          get the users details from the token and set the authentication context
          for the request.
        */

        String username = jwtUtil.getUsername(token);
        UserDetails userDetails = userDetailsService.loadUserByUsername(username);

        UsernamePasswordAuthenticationToken authentication =
            new UsernamePasswordAuthenticationToken(
                userDetails, null, userDetails.getAuthorities());

        authentication.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));
        SecurityContextHolder.getContext().setAuthentication(authentication);
        // Add username to the log field for security (traceability).
        MDC.put("username", userDetails.getUsername());
      }
    }

    // Pass request to next filter in the chain.
    filterChain.doFilter(request, response);
    // Clear the username field added to the log.
    MDC.clear();
  }
}
