-- =========================
-- Authentication / Authorization tables
-- =========================

CREATE TABLE app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

ALTER TABLE app_user
  ADD CONSTRAINT uq_app_user_email UNIQUE (email);

CREATE TABLE app_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

ALTER TABLE app_role
  ADD CONSTRAINT uq_app_role_name UNIQUE (name);

CREATE TABLE app_user_role (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (user_id, role_id),

  CONSTRAINT fk_user_role_user
    FOREIGN KEY (user_id) REFERENCES app_user(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_user_role_role
    FOREIGN KEY (role_id) REFERENCES app_role(id)
    ON DELETE CASCADE
);

CREATE INDEX idx_app_user_role_user ON app_user_role(user_id);
CREATE INDEX idx_app_user_role_role ON app_user_role(role_id);