-- The following schema was generated by ChatGPT (5.2-Thinking model).
-- Reviewed and Edited by Joseph Taylor (ed20jwt).

-- =========================
-- Seed default roles
-- =========================

INSERT INTO app_role(name) VALUES ('ROLE_ADMIN');
INSERT INTO app_role(name) VALUES ('ROLE_USER');