spring.application.name=Coursework-1

# Database Configuration
spring.datasource.url=jdbc:h2:file:./data/db
# Username/Password should be env vars when possible for security purposes.
spring.datasource.username=admin
spring.datasource.password=Q7!mA9#Zr2$ 

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.migration.locations=classpath:db/migration/H2

# JWT Token Properties (Suggested by ChatGPT - see Security package AI_ACKNOWLEDGMENT.md for evidence).
# Secret should be stored in env var when possible for security purposes.
app.jwt.secret: "p9Vx7Qm2Lr8Zt4Hs6Yk1Nw3Bj5Uf0Cd9Xe7Ra2Tv6Gp8Lq4Mz1Ws3Jh0Kn5Yb7Rx"
app.jwt.issuer: "uk-housing-api"
app.jwt.expiration-minutes: 60

# Admin Profile Properties (Suggested by ChatGPT - see Security package AI_ACKNOWLEDGMENT.md for evidence)
# Username/Password should be env vars when possible for security purposes.
app.seed.admin.email=admin@example.com
app.seed.admin.password=admin

# Environment profile - dev/production.
# Used to control application behaviour for different environments.
app.development.environment=false

# Maximum file upload size to APIs.
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB