spring.application.name=Coursework-1

# H2 database chosen for local integration due to simplicity.
# This will not scale beyond local dev, however - as it creates a file.
# Postgres SQL would be a better choice for non-dev environments.

spring.datasource.url=jdbc:h2:file:./data/db
spring.datasource.username=admin
spring.datasource.password=Q7!mA9#Zr2$

# Flyway will create the database automatically (if it doesn't exist) and
# perform migrations on application start.
spring.flyway.enabled=true
spring.flyway.migration.locations=classpath:db/migration/H2

# JWT Token Properties (Suggested by ChatGPT - see Security package README.md for evidence)
# Secret MUST BE CHANGED LATER
app.jwt.secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+_CHARS"
app.jwt.issuer: "uk-housing-api"
app.jwt.expiration-minutes: 60

# Admin Profile Properties (Suggested by ChatGPT - see Security package README.md for evidence)
app.seed.admin.email=admin@example.com
app.seed.admin.password=admin