// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.dal.repository;

import com.uol.comp3011.coursework1.dal.entity.PropertyTransaction;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.annotation.Rollback;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@Rollback
class PropertyTransactionRepositoryTest {

    @Autowired
    private PropertyTransactionRepository repository;

    private PropertyTransaction createTransaction(String town, int price, String postcode, char type, LocalDate date) {
        PropertyTransaction tx = new PropertyTransaction();
        tx.setTransactionUuid(UUID.randomUUID());
        tx.setTownCity(town);
        tx.setPrice(price);
        tx.setPostcode(postcode);
        tx.setPropertyTypeCode(type);
        tx.setTransferDate(date);
        tx.setPpdCategoryCode('A');
        return tx;
    }

    @Test
    @DisplayName("Should return average price per town")
    void averagePriceByTownCity_shouldReturnAggregatedValues() {

        repository.save(createTransaction("Leeds", 200000, "LS1", 'D', LocalDate.of(2020,1,1)));
        repository.save(createTransaction("Leeds", 300000, "LS1", 'D', LocalDate.of(2020,1,2)));
        repository.save(createTransaction("York", 100000, "YO1", 'S', LocalDate.of(2020,1,1)));

        List<PropertyTransactionRepository.AvgPricePerTown> results =
                repository.averagePriceByTownCity(PageRequest.of(0,10));

        assertThat(results).isNotEmpty();
        assertThat(results.stream().map(r -> r.townCity())).contains("Leeds","York");
    }

    @Test
    void averagePriceByTownCityFromTo_shouldFilterDates() {

        repository.save(createTransaction("Leeds", 200000, "LS1", 'D', LocalDate.of(2019,1,1)));
        repository.save(createTransaction("Leeds", 300000, "LS1", 'D', LocalDate.of(2021,1,1)));

        List<PropertyTransactionRepository.AvgPricePerTown> results =
                repository.averagePriceByTownCityFromTo(
                        LocalDate.of(2020,1,1),
                        LocalDate.of(2022,1,1),
                        PageRequest.of(0,10));

        assertThat(results).hasSize(1);
        assertThat(results.get(0).townCity()).isEqualTo("Leeds");
    }

    @Test
    void averagePriceByPostcode_shouldReturnAvgAndCount() {

        repository.save(createTransaction("Leeds", 200000, "LS1", 'D', LocalDate.now()));
        repository.save(createTransaction("Leeds", 300000, "LS1", 'D', LocalDate.now()));

        PropertyTransactionRepository.AvgPrice result =
                repository.averagePriceByPostcode("LS1");

        assertThat(result.avgPrice()).isEqualTo(250000);
        assertThat(result.numSales()).isEqualTo(2);
    }

    @Test
    void getAvailableYears_shouldReturnDistinctYears() {

        repository.save(createTransaction("Leeds", 200000, "LS1", 'D', LocalDate.of(2019,1,1)));
        repository.save(createTransaction("Leeds", 200000, "LS1", 'D', LocalDate.of(2020,1,1)));

        List<Integer> years = repository.getAvailableYears();

        assertThat(years).contains(2019, 2020);
    }
}