// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.dal.repository;

import com.uol.comp3011.coursework1.dal.entity.AppRole;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.test.annotation.Rollback;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@Rollback
class RoleRepositoryTest {

    @Autowired
    private RoleRepository repository;

    @Test
    void findByName_shouldReturnRole() {

        AppRole role = new AppRole();
        role.setName("ROLE_ADMIN_TEST");

        repository.save(role);

        AppRole result = repository.findByName("ROLE_ADMIN_TEST");

        assertThat(result).isNotNull();
        assertThat(result.getName()).isEqualTo("ROLE_ADMIN_TEST");
    }
}