// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View README.md of package for GenAI acknowledgment.

package com.uol.comp3011.Coursework1.Security;

import com.uol.comp3011.Coursework1.Repository.RoleRepository;
import com.uol.comp3011.Coursework1.Repository.UserRepository;
import com.uol.comp3011.Coursework1.Entity.User;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Component;

@Component
public class AdminSeeder implements ApplicationRunner {

    private final UserRepository userRepo;
    private final RoleRepository roleRepo;
    private final BCryptPasswordEncoder encoder;

    @Value("${app.seed.admin.email:admin@example.com}")
    private String adminEmail;

    @Value("${app.seed.admin.password:admin}")
    private String adminPassword;

    public AdminSeeder(UserRepository userRepo,
                       RoleRepository roleRepo,
                       BCryptPasswordEncoder passwordEncoder) {
        this.userRepo = userRepo;
        this.roleRepo = roleRepo;
        this.encoder = passwordEncoder;
    }

    @Override
    @Transactional
    public void run(ApplicationArguments args) {

        User admin = userRepo.findByEmail(adminEmail);
        if(admin == null){
            // If admin user doesn't exist, create it.
            admin = new User();
            admin.setEmail(adminEmail);
            admin.setPasswordHash(encoder.encode(adminPassword));
        }

        admin.getRoles().add(roleRepo.findByName("ROLE_USER"));
        admin.getRoles().add(roleRepo.findByName("ROLE_ADMIN"));

        userRepo.save(admin);
    }
}

