// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.service;

import com.uol.comp3011.coursework1.config.security.JWTUtils;
import com.uol.comp3011.coursework1.dal.entity.AppRole;
import com.uol.comp3011.coursework1.dal.entity.User;
import com.uol.comp3011.coursework1.dal.repository.RoleRepository;
import com.uol.comp3011.coursework1.dal.repository.UserRepository;
import com.uol.comp3011.coursework1.dto.request.UserRequest;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.*;

import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class AuthServiceTest {

    @Mock
    private UserRepository userRepo;

    @Mock
    private RoleRepository roleRepo;

    @Mock
    private AuthenticationManager authenticationManager;

    @Mock
    private BCryptPasswordEncoder encoder;

    @Mock
    private JWTUtils jwtUtils;

    @InjectMocks
    private AuthService authService;

    @BeforeEach
    void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    void createAccount_success() throws Exception {

        UserRequest req = new UserRequest("test@test.com", "password");

        when(userRepo.findByEmail(req.email())).thenReturn(null);
        when(encoder.encode(req.password())).thenReturn("hashed");
    when(roleRepo.findByName("ROLE_USER")).thenReturn(new AppRole());

        authService.createAccount(req);

        verify(userRepo, times(1)).save(any(User.class));
    }

    @Test
    void createAccount_duplicateUser_shouldThrowException() {

        UserRequest req = new UserRequest("test@test.com", "password");

        when(userRepo.findByEmail(req.email())).thenReturn(new User());

        assertThrows(Exception.class, () -> authService.createAccount(req));

        verify(userRepo, never()).save(any());
    }

    @Test
    void login_success_returnsToken() {

        UserRequest req = new UserRequest("test@test.com", "password");

        Authentication auth = mock(Authentication.class);
        UserDetails userDetails = mock(UserDetails.class);

        when(authenticationManager.authenticate(any(UsernamePasswordAuthenticationToken.class)))
                .thenReturn(auth);

        when(auth.getPrincipal()).thenReturn(userDetails);

        when(jwtUtils.generateToken(userDetails)).thenReturn("jwt-token");

        String token = authService.login(req);

        assertEquals("jwt-token", token);
    }
}