// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.service;

import com.uol.comp3011.coursework1.dal.entity.PropertyTransaction;
import com.uol.comp3011.coursework1.dal.repository.PropertyTransactionRepository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.*;

import java.io.ByteArrayInputStream;
import java.util.UUID;

import static org.mockito.Mockito.*;

class DataWriteServiceTest {

    @Mock
    private PropertyTransactionRepository repository;

    @InjectMocks
    private DataWriteService service;

    @BeforeEach
    void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    void deletePpdRecord_shouldDeleteRecord() {

        UUID id = UUID.randomUUID();
        PropertyTransaction tx = new PropertyTransaction();
        tx.setTransactionUuid(id);

        when(repository.findByTransactionUuid(id)).thenReturn(tx);

        service.deletePpdRecord(id.toString());

        verify(repository).delete(tx);
    }

    @Test
    void updatePpdRecord_shouldSaveUpdatedRecord() {

        UUID id = UUID.randomUUID();

        PropertyTransaction existing = new PropertyTransaction();
        existing.setTransactionUuid(id);

        PropertyTransaction updated = new PropertyTransaction();
        updated.setTransactionUuid(id);
        updated.setPrice(100000);

        when(repository.findByTransactionUuid(id)).thenReturn(existing);

        service.updatePpdRecord(updated);

        verify(repository).save(existing);
    }

    @Test
    void uploadPpdYear_shouldSaveParsedRecords() throws Exception {

        String csv =
                "{11111111-1111-1111-1111-111111111111},100000,2023-01-01 00:00,BS1,A,N,F,1,,Street,Loc,Bristol,Dist,County,A";

        ByteArrayInputStream inputStream = new ByteArrayInputStream(csv.getBytes());

        service.uploadPpdYear(inputStream);

        verify(repository, atLeastOnce()).saveAll(any());
    }
}