// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.service;

import com.uol.comp3011.coursework1.dal.entity.PropertyTransaction;
import com.uol.comp3011.coursework1.dal.repository.PropertyTransactionRepository;
import com.uol.comp3011.coursework1.dal.repository.PropertyTransactionRepository.AvgPrice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.*;

import java.sql.SQLException;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class DataReadServiceTest {

    @Mock
    private PropertyTransactionRepository repository;

    @InjectMocks
    private DataReadService service;

    @BeforeEach
    void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    void getAveragePriceByPostcode_success() throws Exception {

        AvgPrice avg = mock(AvgPrice.class);

        when(avg.numSales()).thenReturn(5L);
        when(repository.averagePriceByPostcode("BS1")).thenReturn(avg);

        AvgPrice result = service.getAveragePriceByPostcode("BS1");

        assertEquals(avg, result);
    }

    @Test
    void getAveragePriceByPostcode_noResults_shouldThrow() {

        AvgPrice avg = mock(AvgPrice.class);

        when(avg.numSales()).thenReturn(0L);
        when(repository.averagePriceByPostcode("BS1")).thenReturn(avg);

        assertThrows(SQLException.class,
                () -> service.getAveragePriceByPostcode("BS1"));
    }

    @Test
    void getSingleRecord_success() throws Exception {

        PropertyTransaction tx = new PropertyTransaction();
        UUID id = UUID.randomUUID();

        when(repository.findByTransactionUuid(id)).thenReturn(tx);

        PropertyTransaction result = service.getSingleRecord(id.toString());

        assertEquals(tx, result);
    }

    @Test
    void getSingleRecord_notFound_shouldThrow() {

        UUID id = UUID.randomUUID();

        when(repository.findByTransactionUuid(id)).thenReturn(null);

        assertThrows(SQLException.class,
                () -> service.getSingleRecord(id.toString()));
    }

    @Test
    void getPpdYearsAvailable_success() throws Exception {

        when(repository.getAvailableYears()).thenReturn(List.of(2022, 2023));

        List<Integer> result = service.getPpdYearsAvailable();

        assertEquals(2, result.size());
    }

    @Test
    void getPpdYearsAvailable_empty_shouldThrow() {

        when(repository.getAvailableYears()).thenReturn(List.of());

        assertThrows(SQLException.class,
                () -> service.getPpdYearsAvailable());
    }
}