// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.uol.comp3011.coursework1.config.security.JWTUtils;
import com.uol.comp3011.coursework1.dto.request.UserRequest;
import com.uol.comp3011.coursework1.service.AuthService;
import com.uol.comp3011.coursework1.service.DataReadService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.http.MediaType;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;

import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(AuthController.class)
@AutoConfigureMockMvc(addFilters = false)
class AuthControllerTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Autowired
    private MockMvc mockMvc;

    @MockitoBean
    private AuthService authService;

    @MockitoBean
    private DataReadService dataReadService;

    @MockitoBean
    private JWTUtils jwtUtils;

    @MockitoBean
    private UserDetailsService userDetailsService;


    @Test
    void createAccount_shouldReturn200() throws Exception {

        UserRequest req = new UserRequest("test@test.com", "password");

        doNothing().when(authService).createAccount(req);

        mockMvc.perform(post("/api/v1/auth/create-account")
                        .with(csrf())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(req)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.message").value("Account Created Successfully"));
    }

    @Test
    void createAccount_shouldReturn400_whenMissingFields() throws Exception {

        UserRequest req = new UserRequest("", "");

        mockMvc.perform(post("/api/v1/auth/create-account")
                        .with(csrf())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(req)))
                .andExpect(status().isBadRequest());
    }

    @Test
    void login_shouldReturnToken() throws Exception {

        UserRequest req = new UserRequest("test@test.com", "password");

        when(authService.login(req)).thenReturn("jwt-token");

        mockMvc.perform(post("/api/v1/auth/login")
                        .with(csrf())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(req)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.bearerToken").value("jwt-token"));
    }
}