// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.controller;

import com.uol.comp3011.coursework1.config.security.JWTUtils;
import com.uol.comp3011.coursework1.service.DataReadService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;

import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(DataReadController.class)
class DataReadControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockitoBean
    private DataReadService dataReadService;

    @MockitoBean
    private JWTUtils jwtUtils;

    @MockitoBean
    private UserDetailsService userDetailsService;

    @Test
    @WithMockUser(roles = "USER")
    void getAvailableYears_shouldReturnYears() throws Exception {

        when(dataReadService.getPpdYearsAvailable()).thenReturn(List.of(2020,2021,2022));

        mockMvc.perform(get("/api/v1/read/data/available-years-ppd"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[0]").value(2020));
    }

    @Test
    @WithMockUser(roles = "USER")
    void getAllRecords_shouldReturn200() throws Exception {

        when(dataReadService.getAllRecords(0,100)).thenReturn(List.of());

        mockMvc.perform(get("/api/v1/read/data/all-records"))
                .andExpect(status().isOk());
    }

    @Test
    void getAllRecords_shouldReturn401_withoutAuth() throws Exception {
        mockMvc.perform(get("/api/v1/read/data/all-records"))
                .andExpect(status().isUnauthorized());
    }
}