// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.controller;

import com.uol.comp3011.coursework1.config.security.JWTUtils;
import com.uol.comp3011.coursework1.service.DataReadService;
import com.uol.comp3011.coursework1.service.DataWriteService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;

import static org.mockito.Mockito.doNothing;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.multipart;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(DataWriteController.class)
class DataWriteControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockitoBean
    private DataWriteService dataWriteService;

    @MockitoBean
    private DataReadService dataReadService;

    @MockitoBean
    private JWTUtils jwtUtils;

    @MockitoBean
    private UserDetailsService userDetailsService;


    @Test
    @WithMockUser(roles = "ADMIN")
    void uploadPpdYear_shouldReturn200() throws Exception {

        MockMultipartFile file =
                new MockMultipartFile("file","test.csv","text/csv","data".getBytes());

        doNothing().when(dataWriteService).uploadPpdYear(file.getInputStream());

        mockMvc.perform(multipart("/api/v1/write/admin/upload-ppd-year")
                        .file(file).with(csrf()))
                .andExpect(status().isOk());
    }

    @Test
    @WithMockUser(roles = "ADMIN")
    void uploadPpdYear_shouldReturn500_ifWrongFileType() throws Exception {

        MockMultipartFile file =
                new MockMultipartFile("file","test.txt","text/plain","data".getBytes());

        mockMvc.perform(multipart("/api/v1/write/admin/upload-ppd-year")
                        .file(file).with(csrf()))
                .andExpect(status().isInternalServerError());
    }
}