-- The following schema was generated by ChatGPT (5.2-Thinking model).
-- Reviewed and Edited by Joseph Taylor (ed20jwt).


-- =========================
-- Authentication / Authorization tables
-- =========================

CREATE TABLE app_user (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,

  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,

  created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  updated_at DATETIME2
);

ALTER TABLE app_user
  ADD CONSTRAINT uq_app_user_email UNIQUE (email);

CREATE TABLE app_role (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

ALTER TABLE app_role
  ADD CONSTRAINT uq_app_role_name UNIQUE (name);

CREATE TABLE app_user_role (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  assigned_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  PRIMARY KEY (user_id, role_id),

  CONSTRAINT fk_user_role_user
    FOREIGN KEY (user_id) REFERENCES app_user(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_user_role_role
    FOREIGN KEY (role_id) REFERENCES app_role(id)
    ON DELETE CASCADE
);

CREATE INDEX idx_app_user_role_user ON app_user_role(user_id);
CREATE INDEX idx_app_user_role_role ON app_user_role(role_id);