// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.security;

import com.uol.comp3011.coursework1.config.security.AdminSeeder;
import com.uol.comp3011.coursework1.dal.entity.AppRole;
import com.uol.comp3011.coursework1.dal.entity.User;
import com.uol.comp3011.coursework1.dal.repository.RoleRepository;
import com.uol.comp3011.coursework1.dal.repository.UserRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.boot.ApplicationArguments;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.util.ReflectionTestUtils;

import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class AdminSeederTest {

    @Mock
    private UserRepository userRepo;

    @Mock
    private RoleRepository roleRepo;

    @Mock
    private PasswordEncoder encoder;

    @InjectMocks
    private AdminSeeder adminSeeder;

    @Mock
    private AppRole userRole;

    @Mock
    private AppRole adminRole;

    @Test
    void shouldCreateAdminIfNotExists() throws Exception {

        String email = "admin@test.com";
        String password = "password";

        ReflectionTestUtils.setField(adminSeeder, "adminEmail", email);
        ReflectionTestUtils.setField(adminSeeder, "adminPassword", password);

        when(userRepo.findByEmail(email)).thenReturn(null);
        when(encoder.encode(password)).thenReturn("hashed");
        when(roleRepo.findByName("ROLE_USER")).thenReturn(userRole);
        when(roleRepo.findByName("ROLE_ADMIN")).thenReturn(adminRole);

        adminSeeder.run(mock(ApplicationArguments.class));

        verify(userRepo).save(any(User.class));
    }

    @Test
    void shouldNotCreateAdminIfAlreadyExists() throws Exception {

        String email = "admin@test.com";

        User existingUser = new User();

        ReflectionTestUtils.setField(adminSeeder, "adminEmail", email);

        when(userRepo.findByEmail(email)).thenReturn(existingUser);
        when(roleRepo.findByName("ROLE_USER")).thenReturn(userRole);
        when(roleRepo.findByName("ROLE_ADMIN")).thenReturn(adminRole);

        adminSeeder.run(mock(ApplicationArguments.class));

        verify(userRepo).save(existingUser);
    }
}
