// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.security;

import com.uol.comp3011.coursework1.config.security.DBUserDetailsService;
import com.uol.comp3011.coursework1.dal.entity.AppRole;
import com.uol.comp3011.coursework1.dal.repository.UserRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import com.uol.comp3011.coursework1.dal.entity.User;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UsernameNotFoundException;

import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class DBUserDetailsServiceTest {

    @Mock
    private UserRepository userRepo;

    @InjectMocks
    private DBUserDetailsService service;

    @Test
    void shouldLoadUserSuccessfully() {

        AppRole role = new AppRole();
        role.setName("ROLE_USER");

        User user = new User();
        user.setEmail("test@email.com");
        user.setPasswordHash("password");
        user.setRoles(Set.of(role));

        when(userRepo.findByEmail("test@email.com")).thenReturn(user);

        UserDetails details = service.loadUserByUsername("test@email.com");

        assertEquals("test@email.com", details.getUsername());
        assertEquals("password", details.getPassword());
        assertEquals(1, details.getAuthorities().size());
    }

    @Test
    void shouldThrowExceptionIfUserNotFound() {

        when(userRepo.findByEmail("missing@email.com")).thenReturn(null);

        assertThrows(
                UsernameNotFoundException.class,
                () -> service.loadUserByUsername("missing@email.com")
        );
    }
}