// NOTE: The following code was originally generated by ChatGPT (5.2-Thinking model).
// Reviewed and Edited by Joseph Taylor (ed20jwt) to fit application context.
// View AI_ACKNOWLEDGMENT.md of package for GenAI acknowledgment.

package com.uol.comp3011.coursework1.security;

import com.uol.comp3011.coursework1.config.security.JWTUtils;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class JWTUtilsTest {

    private JWTUtils jwtUtils;

    @BeforeEach
    void setup() {
        jwtUtils = new JWTUtils(
                "12345678901234567890123456789012",
                "test-issuer",
                60
        );
    }

    @Test
    void shouldGenerateAndValidateToken() {

        UserDetails user = User.builder()
                .username("test@email.com")
                .password("password")
                .authorities("ROLE_USER")
                .build();

        String token = jwtUtils.generateToken(user);

        assertTrue(jwtUtils.isValid(token));
    }

    @Test
    void shouldExtractUsername() {

        UserDetails user = User.builder()
                .username("email@test.com")
                .password("password")
                .authorities("ROLE_USER")
                .build();

        String token = jwtUtils.generateToken(user);

        String username = jwtUtils.getUsername(token);

        assertEquals("email@test.com", username);
    }

    @Test
    void shouldExtractRoles() {

        UserDetails user = User.builder()
                .username("user@test.com")
                .password("password")
                .authorities("ROLE_ADMIN")
                .build();

        String token = jwtUtils.generateToken(user);

        List<String> roles = jwtUtils.getRoles(token);

        assertTrue(roles.contains("ROLE_ADMIN"));
    }

    @Test
    void shouldReturnFalseForInvalidToken() {

        boolean valid = jwtUtils.isValid("invalid.token.value");

        assertFalse(valid);
    }
}